const fs = require('fs');
const targetFile = 'packages/nre-packs/worldCountriesData.ts';
const content = fs.readFileSync(targetFile, 'utf8');

// Extract existing country codes
const existingCodes = [...content.matchAll(/countryCode:\s*'([A-Z]{2})'/g)].map(m => m[1]);

const allCountries = [
  {"code":"AF","name":"Afghanistan","region":"asia","currency":"AFN"},
  {"code":"AL","name":"Albania","region":"europe","currency":"ALL"},
  {"code":"DZ","name":"Algeria","region":"africa","currency":"DZD"},
  {"code":"AD","name":"Andorra","region":"europe","currency":"EUR"},
  {"code":"AO","name":"Angola","region":"africa","currency":"AOA"},
  {"code":"AG","name":"Antigua and Barbuda","region":"americas","currency":"XCD"},
  {"code":"AR","name":"Argentina","region":"americas","currency":"ARS"},
  {"code":"AM","name":"Armenia","region":"europe","currency":"AMD"},
  {"code":"AU","name":"Australia","region":"asia","currency":"AUD"},
  {"code":"AT","name":"Austria","region":"europe","currency":"EUR"},
  {"code":"AZ","name":"Azerbaijan","region":"asia","currency":"AZN"},
  {"code":"BS","name":"Bahamas","region":"americas","currency":"BSD"},
  {"code":"BH","name":"Bahrain","region":"middle_east","currency":"BHD"},
  {"code":"BD","name":"Bangladesh","region":"asia","currency":"BDT"},
  {"code":"BB","name":"Barbados","region":"americas","currency":"BBD"},
  {"code":"BY","name":"Belarus","region":"europe","currency":"BYN"},
  {"code":"BE","name":"Belgium","region":"europe","currency":"EUR"},
  {"code":"BZ","name":"Belize","region":"americas","currency":"BZD"},
  {"code":"BJ","name":"Benin","region":"africa","currency":"XOF"},
  {"code":"BT","name":"Bhutan","region":"asia","currency":"BTN"},
  {"code":"BO","name":"Bolivia","region":"americas","currency":"BOB"},
  {"code":"BA","name":"Bosnia and Herzegovina","region":"europe","currency":"BAM"},
  {"code":"BW","name":"Botswana","region":"africa","currency":"BWP"},
  {"code":"BR","name":"Brazil","region":"americas","currency":"BRL"},
  {"code":"BN","name":"Brunei","region":"asia","currency":"BND"},
  {"code":"BG","name":"Bulgaria","region":"europe","currency":"BGN"},
  {"code":"BF","name":"Burkina Faso","region":"africa","currency":"XOF"},
  {"code":"BI","name":"Burundi","region":"africa","currency":"BIF"},
  {"code":"CV","name":"Cabo Verde","region":"africa","currency":"CVE"},
  {"code":"KH","name":"Cambodia","region":"asia","currency":"KHR"},
  {"code":"CM","name":"Cameroon","region":"africa","currency":"XAF"},
  {"code":"CA","name":"Canada","region":"americas","currency":"CAD"},
  {"code":"CF","name":"Central African Republic","region":"africa","currency":"XAF"},
  {"code":"TD","name":"Chad","region":"africa","currency":"XAF"},
  {"code":"CL","name":"Chile","region":"americas","currency":"CLP"},
  {"code":"CN","name":"China","region":"asia","currency":"CNY"},
  {"code":"CO","name":"Colombia","region":"americas","currency":"COP"},
  {"code":"KM","name":"Comoros","region":"africa","currency":"KMF"},
  {"code":"CG","name":"Congo","region":"africa","currency":"XAF"},
  {"code":"CD","name":"Congo (DRC)","region":"africa","currency":"CDF"},
  {"code":"CR","name":"Costa Rica","region":"americas","currency":"CRC"},
  {"code":"HR","name":"Croatia","region":"europe","currency":"EUR"},
  {"code":"CU","name":"Cuba","region":"americas","currency":"CUP"},
  {"code":"CY","name":"Cyprus","region":"europe","currency":"EUR"},
  {"code":"CZ","name":"Czechia","region":"europe","currency":"CZK"},
  {"code":"DK","name":"Denmark","region":"europe","currency":"DKK"},
  {"code":"DJ","name":"Djibouti","region":"africa","currency":"DJF"},
  {"code":"DM","name":"Dominica","region":"americas","currency":"XCD"},
  {"code":"DO","name":"Dominican Republic","region":"americas","currency":"DOP"},
  {"code":"EC","name":"Ecuador","region":"americas","currency":"USD"},
  {"code":"EG","name":"Egypt","region":"middle_east","currency":"EGP"},
  {"code":"SV","name":"El Salvador","region":"americas","currency":"USD"},
  {"code":"GQ","name":"Equatorial Guinea","region":"africa","currency":"XAF"},
  {"code":"ER","name":"Eritrea","region":"africa","currency":"ERN"},
  {"code":"EE","name":"Estonia","region":"europe","currency":"EUR"},
  {"code":"SZ","name":"Eswatini","region":"africa","currency":"SZL"},
  {"code":"ET","name":"Ethiopia","region":"africa","currency":"ETB"},
  {"code":"FJ","name":"Fiji","region":"asia","currency":"FJD"},
  {"code":"FI","name":"Finland","region":"europe","currency":"EUR"},
  {"code":"FR","name":"France","region":"europe","currency":"EUR"},
  {"code":"GA","name":"Gabon","region":"africa","currency":"XAF"},
  {"code":"GM","name":"Gambia","region":"africa","currency":"GMD"},
  {"code":"GE","name":"Georgia","region":"europe","currency":"GEL"},
  {"code":"DE","name":"Germany","region":"europe","currency":"EUR"},
  {"code":"GH","name":"Ghana","region":"africa","currency":"GHS"},
  {"code":"GR","name":"Greece","region":"europe","currency":"EUR"},
  {"code":"GD","name":"Grenada","region":"americas","currency":"XCD"},
  {"code":"GT","name":"Guatemala","region":"americas","currency":"GTQ"},
  {"code":"GN","name":"Guinea","region":"africa","currency":"GNF"},
  {"code":"GW","name":"Guinea-Bissau","region":"africa","currency":"XOF"},
  {"code":"GY","name":"Guyana","region":"americas","currency":"GYD"},
  {"code":"HT","name":"Haiti","region":"americas","currency":"HTG"},
  {"code":"HN","name":"Honduras","region":"americas","currency":"HNL"},
  {"code":"HU","name":"Hungary","region":"europe","currency":"HUF"},
  {"code":"IS","name":"Iceland","region":"europe","currency":"ISK"},
  {"code":"IN","name":"India","region":"asia","currency":"INR"},
  {"code":"ID","name":"Indonesia","region":"asia","currency":"IDR"},
  {"code":"IR","name":"Iran","region":"middle_east","currency":"IRR"},
  {"code":"IQ","name":"Iraq","region":"middle_east","currency":"IQD"},
  {"code":"IE","name":"Ireland","region":"europe","currency":"EUR"},
  {"code":"IL","name":"Israel","region":"middle_east","currency":"ILS"},
  {"code":"IT","name":"Italy","region":"europe","currency":"EUR"},
  {"code":"JM","name":"Jamaica","region":"americas","currency":"JMD"},
  {"code":"JP","name":"Japan","region":"asia","currency":"JPY"},
  {"code":"JO","name":"Jordan","region":"middle_east","currency":"JOD"},
  {"code":"KZ","name":"Kazakhstan","region":"asia","currency":"KZT"},
  {"code":"KE","name":"Kenya","region":"africa","currency":"KES"},
  {"code":"KI","name":"Kiribati","region":"asia","currency":"AUD"},
  {"code":"KP","name":"North Korea","region":"asia","currency":"KPW"},
  {"code":"KR","name":"South Korea","region":"asia","currency":"KRW"},
  {"code":"KW","name":"Kuwait","region":"middle_east","currency":"KWD"},
  {"code":"KG","name":"Kyrgyzstan","region":"asia","currency":"KGS"},
  {"code":"LA","name":"Laos","region":"asia","currency":"LAK"},
  {"code":"LV","name":"Latvia","region":"europe","currency":"EUR"},
  {"code":"LB","name":"Lebanon","region":"middle_east","currency":"LBP"},
  {"code":"LS","name":"Lesotho","region":"africa","currency":"LSL"},
  {"code":"LR","name":"Liberia","region":"africa","currency":"LRD"},
  {"code":"LY","name":"Libya","region":"africa","currency":"LYD"},
  {"code":"LI","name":"Liechtenstein","region":"europe","currency":"CHF"},
  {"code":"LT","name":"Lithuania","region":"europe","currency":"EUR"},
  {"code":"LU","name":"Luxembourg","region":"europe","currency":"EUR"},
  {"code":"MG","name":"Madagascar","region":"africa","currency":"MGA"},
  {"code":"MW","name":"Malawi","region":"africa","currency":"MWK"},
  {"code":"MY","name":"Malaysia","region":"asia","currency":"MYR"},
  {"code":"MV","name":"Maldives","region":"asia","currency":"MVR"},
  {"code":"ML","name":"Mali","region":"africa","currency":"XOF"},
  {"code":"MT","name":"Malta","region":"europe","currency":"EUR"},
  {"code":"MH","name":"Marshall Islands","region":"asia","currency":"USD"},
  {"code":"MR","name":"Mauritania","region":"africa","currency":"MRU"},
  {"code":"MU","name":"Mauritius","region":"africa","currency":"MUR"},
  {"code":"MX","name":"Mexico","region":"americas","currency":"MXN"},
  {"code":"FM","name":"Micronesia","region":"asia","currency":"USD"},
  {"code":"MD","name":"Moldova","region":"europe","currency":"MDL"},
  {"code":"MC","name":"Monaco","region":"europe","currency":"EUR"},
  {"code":"MN","name":"Mongolia","region":"asia","currency":"MNT"},
  {"code":"ME","name":"Montenegro","region":"europe","currency":"EUR"},
  {"code":"MA","name":"Morocco","region":"africa","currency":"MAD"},
  {"code":"MZ","name":"Mozambique","region":"africa","currency":"MZN"},
  {"code":"MM","name":"Myanmar","region":"asia","currency":"MMK"},
  {"code":"NA","name":"Namibia","region":"africa","currency":"NAD"},
  {"code":"NR","name":"Nauru","region":"asia","currency":"AUD"},
  {"code":"NP","name":"Nepal","region":"asia","currency":"NPR"},
  {"code":"NL","name":"Netherlands","region":"europe","currency":"EUR"},
  {"code":"NZ","name":"New Zealand","region":"asia","currency":"NZD"},
  {"code":"NI","name":"Nicaragua","region":"americas","currency":"NIO"},
  {"code":"NE","name":"Niger","region":"africa","currency":"XOF"},
  {"code":"NG","name":"Nigeria","region":"africa","currency":"NGN"},
  {"code":"MK","name":"North Macedonia","region":"europe","currency":"MKD"},
  {"code":"NO","name":"Norway","region":"europe","currency":"NOK"},
  {"code":"OM","name":"Oman","region":"middle_east","currency":"OMR"},
  {"code":"PK","name":"Pakistan","region":"asia","currency":"PKR"},
  {"code":"PW","name":"Palau","region":"asia","currency":"USD"},
  {"code":"PS","name":"Palestine","region":"middle_east","currency":"ILS"},
  {"code":"PA","name":"Panama","region":"americas","currency":"PAB"},
  {"code":"PG","name":"Papua New Guinea","region":"asia","currency":"PGK"},
  {"code":"PY","name":"Paraguay","region":"americas","currency":"PYG"},
  {"code":"PE","name":"Peru","region":"americas","currency":"PEN"},
  {"code":"PH","name":"Philippines","region":"asia","currency":"PHP"},
  {"code":"PL","name":"Poland","region":"europe","currency":"PLN"},
  {"code":"PT","name":"Portugal","region":"europe","currency":"EUR"},
  {"code":"QA","name":"Qatar","region":"middle_east","currency":"QAR"},
  {"code":"RO","name":"Romania","region":"europe","currency":"RON"},
  {"code":"RU","name":"Russia","region":"europe","currency":"RUB"},
  {"code":"RW","name":"Rwanda","region":"africa","currency":"RWF"},
  {"code":"KN","name":"Saint Kitts and Nevis","region":"americas","currency":"XCD"},
  {"code":"LC","name":"Saint Lucia","region":"americas","currency":"XCD"},
  {"code":"VC","name":"Saint Vincent and the Grenadines","region":"americas","currency":"XCD"},
  {"code":"WS","name":"Samoa","region":"asia","currency":"WST"},
  {"code":"SM","name":"San Marino","region":"europe","currency":"EUR"},
  {"code":"ST","name":"Sao Tome and Principe","region":"africa","currency":"STN"},
  {"code":"SA","name":"Saudi Arabia","region":"middle_east","currency":"SAR"},
  {"code":"SN","name":"Senegal","region":"africa","currency":"XOF"},
  {"code":"RS","name":"Serbia","region":"europe","currency":"RSD"},
  {"code":"SC","name":"Seychelles","region":"africa","currency":"SCR"},
  {"code":"SL","name":"Sierra Leone","region":"africa","currency":"SLL"},
  {"code":"SG","name":"Singapore","region":"asia","currency":"SGD"},
  {"code":"SK","name":"Slovakia","region":"europe","currency":"EUR"},
  {"code":"SI","name":"Slovenia","region":"europe","currency":"EUR"},
  {"code":"SB","name":"Solomon Islands","region":"asia","currency":"SBD"},
  {"code":"SO","name":"Somalia","region":"africa","currency":"SOS"},
  {"code":"ZA","name":"South Africa","region":"africa","currency":"ZAR"},
  {"code":"SS","name":"South Sudan","region":"africa","currency":"SSP"},
  {"code":"ES","name":"Spain","region":"europe","currency":"EUR"},
  {"code":"LK","name":"Sri Lanka","region":"asia","currency":"LKR"},
  {"code":"SD","name":"Sudan","region":"africa","currency":"SDG"},
  {"code":"SR","name":"Suriname","region":"americas","currency":"SRD"},
  {"code":"SE","name":"Sweden","region":"europe","currency":"SEK"},
  {"code":"CH","name":"Switzerland","region":"europe","currency":"CHF"},
  {"code":"SY","name":"Syria","region":"middle_east","currency":"SYP"},
  {"code":"TW","name":"Taiwan","region":"asia","currency":"TWD"},
  {"code":"TJ","name":"Tajikistan","region":"asia","currency":"TJS"},
  {"code":"TZ","name":"Tanzania","region":"africa","currency":"TZS"},
  {"code":"TH","name":"Thailand","region":"asia","currency":"THB"},
  {"code":"TL","name":"Timor-Leste","region":"asia","currency":"USD"},
  {"code":"TG","name":"Togo","region":"africa","currency":"XOF"},
  {"code":"TO","name":"Tonga","region":"asia","currency":"TOP"},
  {"code":"TT","name":"Trinidad and Tobago","region":"americas","currency":"TTD"},
  {"code":"TN","name":"Tunisia","region":"africa","currency":"TND"},
  {"code":"TR","name":"Turkey","region":"middle_east","currency":"TRY"},
  {"code":"TM","name":"Turkmenistan","region":"asia","currency":"TMT"},
  {"code":"TV","name":"Tuvalu","region":"asia","currency":"AUD"},
  {"code":"UG","name":"Uganda","region":"africa","currency":"UGX"},
  {"code":"UA","name":"Ukraine","region":"europe","currency":"UAH"},
  {"code":"AE","name":"United Arab Emirates","region":"middle_east","currency":"AED"},
  {"code":"GB","name":"United Kingdom","region":"europe","currency":"GBP"},
  {"code":"US","name":"United States","region":"americas","currency":"USD"},
  {"code":"UY","name":"Uruguay","region":"americas","currency":"UYU"},
  {"code":"UZ","name":"Uzbekistan","region":"asia","currency":"UZS"},
  {"code":"VU","name":"Vanuatu","region":"asia","currency":"VUV"},
  {"code":"VA","name":"Vatican City","region":"europe","currency":"EUR"},
  {"code":"VE","name":"Venezuela","region":"americas","currency":"VES"},
  {"code":"VN","name":"Vietnam","region":"asia","currency":"VND"},
  {"code":"YE","name":"Yemen","region":"middle_east","currency":"YER"},
  {"code":"ZM","name":"Zambia","region":"africa","currency":"ZMW"},
  {"code":"ZW","name":"Zimbabwe","region":"africa","currency":"ZWL"}
];

let newEntries = '';
let addedCount = 0;

allCountries.forEach(c => {
  if (!existingCodes.includes(c.code)) {
    newEntries += `  {
    countryCode: '${c.code}',
    countryName: '${c.name.replace(/'/g, "\\'")}',
    regionCode: '${c.region}',
    currencyCode: '${c.currency}',
    primaryLanguage: 'en',
    languages: ['en'],
    legalSystem: 'mixed',
    scannerLegalGate: 'standard',
    dataResidencyRequired: false,
    regulators: []
  },\n`;
    addedCount++;
  }
});

if (addedCount > 0) {
    const insertIndex = content.lastIndexOf('];');
    if (insertIndex !== -1) {
        const newContent = content.slice(0, insertIndex) + newEntries + content.slice(insertIndex);
        fs.writeFileSync(targetFile, newContent);
        console.log(`Added ${addedCount} new countries.`);
    }
} else {
    console.log('All countries already present.');
}
