import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Globe,
  Settings,
  Code,
  History,
  FileText,
  Copy,
  Check,
  CheckCircle,
  Database,
  CloudLightning,
  Sparkles,
  RefreshCw,
  Palette,
  Layout,
  Sliders,
  Terminal,
  Upload,
  Link,
  Save,
  HelpCircle,
  AlertCircle,
  FileSignature,
  ArrowRight
} from 'lucide-react';
import { PrivacyPolicyWizard } from './PrivacyPolicyWizard';

// ==========================================
// TYPES AND INTERFACES
// ==========================================

export interface PolicyBlock {
  id: string;
  title: string;
  version: string;
  lastUpdated: string;
  applicableLaw: string;
  status: 'Published' | 'Draft' | 'Requires Review';
  summary: string;
  content: string;
}

export interface DeploymentTarget {
  id: string;
  name: string;
  type: 'web' | 'mobile' | 'intranet';
  status: 'Synced' | 'Pending Sync' | 'Failed';
  lastPing: string;
  endpointUrl: string;
}

export function EuCompliancePortalConfigurator() {
  const [activeView, setActiveView] = useState<'distribution' | 'wizard'>('wizard');

  const handleSyncGeneratedPolicy = (generated: { title: string; applicableLaw: string; content: string }) => {
    setPolicies(prev => {
      const exists = prev.some(p => p.id === 'p-generated');
      if (exists) {
        return prev.map(p => p.id === 'p-generated' ? {
          ...p,
          title: generated.title,
          applicableLaw: generated.applicableLaw,
          content: generated.content,
          lastUpdated: new Date().toISOString().split('T')[0]
        } : p);
      } else {
        return [
          {
            id: 'p-generated',
            title: generated.title,
            version: 'V1.0',
            lastUpdated: new Date().toISOString().split('T')[0],
            applicableLaw: generated.applicableLaw,
            status: 'Draft',
            summary: 'Custom compliance policy dynamically generated by client relative to specific tracker inventory details.',
            content: generated.content
          },
          ...prev
        ];
      }
    });
    setSelectedPolicyId('p-generated');
    setActiveView('distribution');
  };

  // ==========================================
  // PANEL 1 STATE: HEADLESS COMPLIANCE CMS
  // ==========================================
  const [policies, setPolicies] = useState<PolicyBlock[]>([
    {
      id: 'p1',
      title: 'Global Privacy Policy & Data Hygiene Directive',
      version: 'V4.2',
      lastUpdated: '2026-06-12',
      applicableLaw: 'GDPR Directive Article 13 & 14',
      status: 'Published',
      summary: 'Aggressive consent mechanics framework routing outbound cookie payloads safely across 27 EU member states.',
      content: 'We process personal information using cryptographic token matching in strict accordance with GDPR Article 13/14 guidelines...'
    },
    {
      id: 'p2',
      title: 'AI Act Algorithmic Transparency Disclosure',
      version: 'V1.0',
      lastUpdated: '2026-06-11',
      applicableLaw: 'EU AI Act Title III High-Risk Systems',
      status: 'Published',
      summary: 'Public statement identifying neural networks weight matrices bias controls on demographic loan scoring.',
      content: 'Autonomous risk mitigation is fully deployed under safety envelope controls protecting resident loan scorers from localized biases...'
    },
    {
      id: 'p3',
      title: 'E-Commerce Cookie Consent Configuration',
      version: 'V3.1',
      lastUpdated: '2026-06-13',
      applicableLaw: 'EU ePrivacy Directive (Art 5.3)',
      status: 'Draft',
      summary: 'Granular consent filters managing analytical trackers and non-consensual default state blockers.',
      content: 'Explicit telemetry cookies are persistently held back until digital keys are selected by end-users in our web UI.'
    }
  ]);

  const [deploymentTargets, setDeploymentTargets] = useState<DeploymentTarget[]>([
    { id: 't1', name: 'Main Corporate Website', type: 'web', status: 'Synced', lastPing: '3 mins ago', endpointUrl: 'https://clientname.com' },
    { id: 't2', name: 'Mobile iOS/Android Apps', type: 'mobile', status: 'Synced', lastPing: '12 mins ago', endpointUrl: 'https://api.clientname.com/v1/compliance' },
    { id: 't3', name: 'Enterprise Internal Legal Portal', type: 'intranet', status: 'Pending Sync', lastPing: 'Never synced', endpointUrl: 'https://intranet.secure.clientname.internal' }
  ]);

  const [selectedPolicyId, setSelectedPolicyId] = useState<string>('p1');
  const [publishingLog, setPublishingLog] = useState<string[]>([]);
  const [isPublishing, setIsPublishing] = useState<boolean>(false);

  // ==========================================
  // PANEL 2 STATE: EMBEDDABLE SCRIPT & CONSENT CONFIGURATOR
  // ==========================================
  const [tenantId, setTenantId] = useState<string>('9841');
  const [isCopied, setIsCopied] = useState<boolean>(false);
  const [bannerPlacement, setBannerPlacement] = useState<'bottom-center' | 'bottom-right' | 'top-banner' | 'modal'>('bottom-center');
  const [cookieScanThreshold, setCookieScanThreshold] = useState<number>(100);
  const [customBannerText, setCustomBannerText] = useState<string>('We utilize cookie tokens to assure sovereign EU compliance.');
  const [allowGranularToggle, setAllowGranularToggle] = useState<boolean>(true);

  // ==========================================
  // PANEL 3 STATE: IMMUTABLE HISTORIC TIMELINE
  // ==========================================
  const [activeDiffIndex, setActiveDiffIndex] = useState<number>(0);
  const diffs = [
    {
      date: 'Modified June 12, 2026',
      summary: 'Aligned with AI Act High-Risk Model Mandates',
      sha: 'SHA-256: 0x93FA..C821',
      removed: 'Non-deterministic user models require post-facto audit checkups outside of sovereign EU databases.',
      added: 'All demographic loan scoring parameters are checked prior to weight deployment in real-time matching.'
    },
    {
      date: 'Modified June 10, 2026',
      summary: 'GDPR Cross-Border Egress Check',
      sha: 'SHA-256: 0x41E9..D882',
      removed: 'Analytics trackers may load upon user viewport initiation preceding the active choice.',
      added: 'Optional trackers are hard paused until active explicit opt-in confirmation is logged per server IP.'
    }
  ];

  // ==========================================
  // PANEL 4 STATE: WHITE-LABEL BRANDING CMS
  // ==========================================
  const [customDomain, setCustomDomain] = useState<string>('compliance.clientname.com');
  const [primaryBrandColor, setPrimaryBrandColor] = useState<string>('#0984E3');
  const [typographyFont, setTypographyFont] = useState<string>('sans');
  const [borderRadius, setBorderRadius] = useState<number>(12);
  const [isLogoUploaded, setIsLogoUploaded] = useState<boolean>(true);
  const [webhookUrl, setWebhookUrl] = useState<string>('https://webhook.clientname.com/compliance-receiver');
  const [brandingNotification, setBrandingNotification] = useState<string | null>(null);

  const handleApplyBranding = () => {
    setBrandingNotification(`White-label branding configurations synchronized! Customized domain mapped: ${customDomain}`);
    setTimeout(() => {
      setBrandingNotification(null);
    }, 4000);
  };

  // ==========================================
  // HANDLERS
  // ==========================================

  const handleCopyCode = () => {
    const generatedScript = `<script src="https://api.regulettee.eu/v1/compliance.js?tenant=${tenantId}&theme=${encodeURIComponent(primaryBrandColor)}&rounded=${borderRadius}" defer></script>`;
    navigator.clipboard.writeText(generatedScript);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handlePublishAcrossEurope = () => {
    setIsPublishing(true);
    setPublishingLog([]);
    const logs = [
      '🚀 Initiating handshake with CDN proxy nodes...',
      '🔗 Encrypting block metadata using TLS 1.3 key pairing...',
      '🌐 Synchronizing 27 sovereign regional European edge-caches...',
      '✅ Global propagation finalized. 9Xen Regulettee compliant manifest is Live!'
    ];

    logs.forEach((logContent, idx) => {
      setTimeout(() => {
        setPublishingLog(prev => [...prev, logContent]);
        if (idx === logs.length - 1) {
          setIsPublishing(false);
          // Update draft policy to Published
          setPolicies(prev => prev.map(p => p.id === 'p3' ? { ...p, status: 'Published' } : p));
          // Mark intranets as synced
          setDeploymentTargets(prev => prev.map(t => ({ ...t, status: 'Synced' })));
        }
      }, (idx + 1) * 700);
    });
  };

  const currentSelectedPolicy = policies.find(p => p.id === selectedPolicyId) || policies[0];

  return (
    <div className="bg-slate-50 text-slate-800 font-sans border-t-4 border-[#0984E3]" id="compliance_portal_portal_configurator">
      
      {/* ================= HEADER BRANDING ================= */}
      <div className="bg-white border-b border-slate-200 py-4 sm:py-6 px-4 md:px-8 shadow-xs">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="bg-[#0984E3]/10 text-[#0984E3] text-[10px] uppercase font-black tracking-widest px-2.5 py-0.5 rounded-full flex items-center gap-1">
                <Globe className="h-3 w-3" /> Distribution Engine Live
              </span>
              <span className="text-[10px] text-slate-500 font-mono">WHITE-LABEL PORTAL DESK: TENANT-{tenantId}</span>
            </div>
            <h1 className="text-2xl md:text-3xl font-black tracking-tight text-[#0984E3] font-display uppercase">
              Client Protection & Document Desk
            </h1>
            <p className="text-xs text-slate-500 font-medium">
              Generate fully compliant GDPR Privacy Policies, configure embeddable web cookie banners, and propagate assets live over CDNs.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <div className="bg-slate-900 text-white py-1.5 px-3 rounded-lg text-[10.5px] font-mono flex items-center gap-2 shadow-sm">
              <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
              <span>EU CDN Security: Active</span>
            </div>
          </div>
        </div>
      </div>

      {/* ================= SUB NAVIGATION TABS ================= */}
      <div className="bg-slate-100/80 border-b border-slate-200 py-3.5 px-4 md:px-8 shadow-inner">
        <div className="max-w-7xl mx-auto flex items-center justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-black uppercase tracking-wider text-slate-500 font-mono">
              Workspace Segment:
            </span>
          </div>
          
          <div className="flex bg-white p-1 rounded-xl border border-slate-200/80 shadow-xs">
            <button
              onClick={() => setActiveView('wizard')}
              type="button"
              className={`px-4 py-1.5 rounded-lg text-xs font-black transition-all cursor-pointer flex items-center gap-1.5 ${
                activeView === 'wizard'
                  ? 'bg-indigo-600 text-white shadow-xs'
                  : 'text-slate-600 hover:text-indigo-600 hover:bg-slate-50'
              }`}
            >
              <FileSignature className="h-3.5 w-3.5" />
              Step-by-Step Privacy Policy Wizard
            </button>
            <button
              onClick={() => setActiveView('distribution')}
              type="button"
              className={`px-4 py-1.5 rounded-lg text-xs font-black transition-all cursor-pointer flex items-center gap-1.5 ${
                activeView === 'distribution'
                  ? 'bg-[#0984E3] text-white shadow-xs'
                  : 'text-slate-600 hover:text-[#0984E3] hover:bg-slate-50'
              }`}
            >
              <Globe className="h-3.5 w-3.5" />
              CDN Headless CMS & Whitelabel Widget
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto p-4 md:p-6 space-y-4 sm:space-y-6">
        {activeView === 'wizard' ? (
          <PrivacyPolicyWizard
            onSyncPolicy={handleSyncGeneratedPolicy}
            initialWebsiteUrl="https://clientname.com"
            initialBusinessLocation="Ireland"
          />
        ) : (
          <>

        {/* ================= PANEL 1: HEADLESS COMPLIANCE CMS & MULTI-CHANNEL DISTRIBUTION HUB ================= */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden" id="headless_compliance_cms">
          <div className="p-5 bg-gradient-to-r from-slate-900 to-slate-950 text-white flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div className="space-y-1">
              <span className="bg-[#6C5CE7] text-white text-[9px] font-mono px-2 py-0.5 rounded">HEADLESS CONTENT BLOCK ENGINE</span>
              <h2 className="text-base font-extrabold text-slate-100 flex items-center gap-2 font-mono">
                <Database className="h-4.5 w-4.5 text-[#0984E3]" /> Public Policy Content Management System (CMS)
              </h2>
              <p className="text-xs text-slate-400">
                Manage compliance directives and push live static legal documents down multi-channel webhook networks.
              </p>
            </div>
            
            <button
              onClick={handlePublishAcrossEurope}
              disabled={isPublishing}
              className="w-full md:w-auto px-5 py-2.5 bg-[#0984E3] hover:bg-[#076bba] text-xs font-mono font-black text-white rounded-xl transition-all cursor-pointer flex items-center justify-center gap-2 shadow-sm disabled:opacity-50"
            >
              <CloudLightning className="h-4 w-4" /> 
              {isPublishing ? 'Propagating to CDN Gateways...' : 'Publish Live Updates Across All Regional Localized Nodes (27 EU Countries)'}
            </button>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 divide-y lg:divide-y-0 lg:divide-x divide-slate-250">
            {/* CMS Policies selector */}
            <div className="lg:col-span-5 p-5 space-y-3.5 bg-slate-50/50">
              <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider font-mono">SELECT COMPLIANCE INSTANCE</span>
              
              <div className="space-y-2">
                {policies.map(block => (
                  <button
                    key={block.id}
                    onClick={() => setSelectedPolicyId(block.id)}
                    className={`w-full text-left p-3.5 rounded-xl border transition-all flex flex-col justify-between gap-1.5 cursor-pointer ${
                      selectedPolicyId === block.id 
                        ? 'bg-white border-[#0984E3] ring-2 ring-[#0984E3]/10 shadow-sm'
                        : 'bg-white/80 hover:bg-white border-slate-200'
                    }`}
                  >
                    <div className="flex justify-between items-start gap-2">
                      <span className="font-extrabold text-xs text-slate-900 leading-tight block">
                        {block.title}
                      </span>
                      <span className={`text-[8.5px] font-black px-2 py-0.5 rounded font-mono ${
                        block.status === 'Published' ? 'bg-emerald-50 text-emerald-700 border border-emerald-100' : 'bg-amber-50 text-amber-700'
                      }`}>
                        {block.status === 'Published' ? `${block.version} // Live` : `${block.version} // Draft`}
                      </span>
                    </div>
                    <p className="text-[11px] text-slate-500 line-clamp-2">{block.summary}</p>
                    <div className="flex items-center justify-between text-[9px] text-slate-400 font-mono pt-1.5 border-t border-slate-100/50">
                      <span>Ref: {block.applicableLaw}</span>
                      <span>Updated: {block.lastUpdated}</span>
                    </div>
                  </button>
                ))}
              </div>
            </div>

            {/* Content preview and deployment pipelines */}
            <div className="lg:col-span-7 p-5 space-y-5">
              <div className="space-y-1.5">
                <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider font-mono block">RAW TEXT EDIT COMPILER</span>
                <div className="border border-slate-200 rounded-xl overflow-x-auto shadow-xs bg-slate-50">
                  <div className="p-3 bg-slate-100 border-b border-slate-200 flex justify-between items-center text-[10px] font-mono text-slate-500">
                    <span>Sovereign ID: [DOC-{currentSelectedPolicy.id.toUpperCase()}]</span>
                    <span>Format: Plaintext Compliant String</span>
                  </div>
                  <textarea
                    value={currentSelectedPolicy.content}
                    onChange={(e) => {
                      const newContent = e.target.value;
                      setPolicies(prev => prev.map(p => p.id === currentSelectedPolicy.id ? { ...p, content: newContent } : p));
                    }}
                    className="w-full h-28 p-3 bg-white text-xs font-mono text-slate-800 focus:outline-none resize-none border-0"
                  />
                  <div className="p-2.5 bg-slate-100 border-t border-slate-100 text-[10px] flex justify-between text-slate-500 font-mono">
                    <span>Applicability: <span className="text-[#0984E3] font-bold">{currentSelectedPolicy.applicableLaw}</span></span>
                    <span>Characters: {currentSelectedPolicy.content.length}</span>
                  </div>
                </div>
              </div>

              {/* Multi-platform channel connectors */}
              <div className="space-y-2">
                <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider font-mono block">ACTIVE SYNC PIPELINES</span>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  {deploymentTargets.map(target => (
                    <div key={target.id} className="p-3 bg-slate-50 border border-slate-200 rounded-xl flex flex-col justify-between gap-2 shadow-xs">
                      <div className="flex items-center justify-between gap-1.5">
                        <span className="font-extrabold text-[11px] text-slate-900 truncate">{target.name}</span>
                        <span className={`h-2 w-2 rounded-full ${
                          target.status === 'Synced' ? 'bg-emerald-500 animate-pulse' : 'bg-amber-400'
                        }`} />
                      </div>
                      <div className="text-[9px] font-mono text-slate-400 truncate">
                        {target.endpointUrl}
                      </div>
                      <div className="flex justify-between items-center pt-1 border-t border-slate-200/50 text-[9px] font-mono text-slate-500">
                        <span>{target.status}</span>
                        <span>{target.lastPing}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Publish Progress Console */}
              {isPublishing && (
                <div className="bg-slate-900 rounded-xl p-3 font-mono text-[10px] text-slate-300 space-y-1 border-l-2 border-[#0984E3]">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-1 text-[#0984E3] font-extrabold">
                    <span>SOVEREIGN CLOUD PROPAGATION LOG</span>
                    <RefreshCw className="h-3 w-3 animate-spin" />
                  </div>
                  {publishingLog.map((log, index) => (
                    <div key={index} className="flex gap-2">
                      <span className="text-slate-500">[{index + 1}]</span>
                      <span>{log}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </section>


        {/* ================= PANEL 2: LIVE EMBEDDABLE SCRIPT GENERATOR & SMART COOKIE-CONSENT UI BUILDER ================= */}
        <section className="grid grid-cols-1 lg:grid-cols-12 gap-4 sm:gap-6" id="embeddable_script_configurator">
          
          {/* Script Generator & Design Parameters */}
          <div className="lg:col-span-7 bg-white rounded-2xl border border-slate-200 shadow-xs p-5 flex flex-col justify-between gap-5">
            <div className="space-y-1.5">
              <span className="bg-[#0984E3]/10 text-[#0984E3] text-[9px] font-black font-mono px-2 py-0.5 rounded">
                INTEGRATION IDE
              </span>
              <h3 className="text-base font-extrabold text-[#1B3A4B] font-display">
                Dynamic Embeddable Compliance SDK Generator
              </h3>
              <p className="text-xs text-slate-500 font-medium">
                Generate high-performance script payloads to inject our compliant widget layers straight into corporate pages.
              </p>
            </div>

            {/* Generated Script Payload Block */}
            <div className="space-y-2">
              <span className="text-[10px] font-black text-slate-400 uppercase font-mono block">LIVE SDK LOADER SNIPPET</span>
              <div className="relative">
                <pre className="bg-slate-900 text-slate-250 p-3.5 rounded-xl text-[11px] font-mono overflow-x-auto border-l-4 border-[#6C5CE7] leading-relaxed">
                  {`<script src="https://api.regulettee.eu/v1/compliance.js?tenant=${tenantId}&theme=${encodeURIComponent(primaryBrandColor)}&rounded=${borderRadius}" defer></script>`}
                </pre>
                <button
                  onClick={handleCopyCode}
                  className="absolute right-2 top-2 p-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded hover:text-white transition-all cursor-pointer shadow-sm"
                >
                  {isCopied ? <span className="text-[9px] font-bold text-emerald-400 font-mono">Copied Check!</span> : <Copy className="h-3.5 w-3.5" />}
                </button>
              </div>
            </div>

            {/* Design Customization Sliders */}
            <div className="space-y-3 pt-3 border-t border-slate-100">
              <span className="text-[10px] font-black text-slate-400 uppercase font-mono block">BANNER DESIGN CUSTOMIZATION SLIDERS</span>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Placement buttons */}
                <div className="space-y-2">
                  <label className="text-[10px] font-bold text-slate-500 uppercase font-mono block">Compliance Banner Position</label>
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <button
                      onClick={() => setBannerPlacement('bottom-center')}
                      className={`py-1.5 px-3 rounded-lg border font-bold font-mono text-[10px] cursor-pointer transition-all ${
                        bannerPlacement === 'bottom-center' ? 'bg-[#0984E3] text-white border-transparent' : 'bg-slate-50 hover:bg-slate-100 border-slate-200/60'
                      }`}
                    >
                      Bottom Center
                    </button>
                    <button
                      onClick={() => setBannerPlacement('bottom-right')}
                      className={`py-1.5 px-3 rounded-lg border font-bold font-mono text-[10px] cursor-pointer transition-all ${
                        bannerPlacement === 'bottom-right' ? 'bg-[#0984E3] text-white border-transparent' : 'bg-slate-50 hover:bg-slate-100 border-slate-200/60'
                      }`}
                    >
                      Bottom Right
                    </button>
                    <button
                      onClick={() => setBannerPlacement('top-banner')}
                      className={`py-1.5 px-3 rounded-lg border font-bold font-mono text-[10px] cursor-pointer transition-all ${
                        bannerPlacement === 'top-banner' ? 'bg-[#0984E3] text-white border-transparent' : 'bg-slate-50 hover:bg-slate-100 border-slate-200/60'
                      }`}
                    >
                      Top Banner
                    </button>
                    <button
                      onClick={() => setBannerPlacement('modal')}
                      className={`py-1.5 px-3 rounded-lg border font-bold font-mono text-[10px] cursor-pointer transition-all ${
                        bannerPlacement === 'modal' ? 'bg-[#0984E3] text-white border-transparent' : 'bg-slate-50 hover:bg-slate-100 border-slate-200/60'
                      }`}
                    >
                      Modal Overlay
                    </button>
                  </div>
                </div>

                {/* Scan Threshold slider */}
                <div className="space-y-2">
                  <div className="flex justify-between items-center text-[10px] font-bold text-slate-500 uppercase font-mono">
                    <label>Cookie Scan Throttling</label>
                    <span className="text-[#0984E3]">{cookieScanThreshold} Domains / Sec</span>
                  </div>
                  <input
                    type="range"
                    min="10"
                    max="500"
                    value={cookieScanThreshold}
                    onChange={(e) => setCookieScanThreshold(parseInt(e.target.value))}
                    className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#0984E3]"
                  />
                  <div className="flex justify-between text-[9px] text-slate-400 font-mono">
                    <span>10 Limit</span>
                    <span>Low latency balancing</span>
                    <span>500 Max</span>
                  </div>
                </div>
              </div>

              {/* Text Injection Config */}
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-slate-500 uppercase font-mono block">Consent Banner Injection Text</label>
                <input
                  type="text"
                  value={customBannerText}
                  onChange={(e) => setCustomBannerText(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-50 focus:bg-white text-xs border border-slate-200 rounded-lg outline-none focus:ring-1 focus:ring-[#0984E3]"
                />
              </div>

              <div className="flex items-center gap-3">
                <input 
                  type="checkbox"
                  id="granular_enabled"
                  checked={allowGranularToggle}
                  onChange={(e) => setAllowGranularToggle(e.target.checked)}
                  className="rounded text-[#0984E3] focus:ring-[#0984E3] cursor-pointer"
                />
                <label htmlFor="granular_enabled" className="text-xs font-semibold text-slate-600 cursor-pointer">
                  Force granular checklists for analytical cookies tracking state
                </label>
              </div>
            </div>
          </div>

          {/* Visual Consent Banner Configurator Interactive Preview */}
          <div className="lg:col-span-5 bg-white rounded-2xl border border-slate-200 shadow-xs p-5 flex flex-col justify-between gap-4">
            <div className="space-y-1 pb-3 border-b border-slate-100">
              <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider font-mono block">INTEGRATED VISUAL PREVIEW</span>
              <h4 className="text-xs font-extrabold text-slate-900 font-mono">Active Consent Banner Preview Sandbox</h4>
              <p className="text-[11px] text-slate-500 leading-relaxed">
                Render sandbox showing how the customer-facing cookie controller pop-up dynamically updates with selected styles.
              </p>
            </div>

            {/* Simulated Live Frame Box */}
            <div className="bg-slate-100 border border-slate-200 rounded-xl p-4 h-64 relative flex items-center justify-center overflow-hidden">
              <span className="absolute top-2 left-2 text-[8px] font-mono text-slate-400 bg-white/80 px-1.5 py-0.5 rounded shadow-xs">
                Static Page Simulator Frame
              </span>
              
              <div className="text-center text-[10px] text-slate-400 uppercase select-none space-y-1 font-mono">
                <div>[Mock Application Background Canvas]</div>
                <div>compliance.clientname.com</div>
              </div>

              {/* FLOATING CONSENT BANNER INTERACTIVE OVERLAY */}
              <div 
                className={`absolute bg-white border border-slate-200 p-3.5 shadow-xl transition-all duration-300 max-w-xs ${
                  bannerPlacement === 'bottom-center' ? 'bottom-3 mx-auto left-4 right-4' :
                  bannerPlacement === 'bottom-right' ? 'bottom-3 right-3 left-auto' :
                  bannerPlacement === 'top-banner' ? 'top-3 left-3 right-3' :
                  'top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-4/5'
                }`}
                style={{
                  borderRadius: `${borderRadius}px`,
                  borderColor: primaryBrandColor + '30',
                  boxShadow: '0 8px 30px rgba(0, 0, 0, 0.08)'
                }}
              >
                <div className="flex items-start gap-2">
                  <span className="p-1 text-white rounded shrink-0 h-5 w-5 flex items-center justify-center text-[10px]" style={{ backgroundColor: primaryBrandColor }}>
                    🍪
                  </span>
                  <div className="space-y-1 text-left">
                    <span className="text-[11.5px] font-extrabold text-slate-900 leading-tight block">
                      Cookie compliance request
                    </span>
                    <p className="text-[10px] text-slate-500 leading-normal font-sans">
                      {customBannerText}
                    </p>
                  </div>
                </div>

                {allowGranularToggle && (
                  <div className="mt-2.5 pt-2 border-t border-slate-100 flex justify-between text-[9px] font-mono text-slate-500">
                    <label className="flex items-center gap-1">
                      <input type="checkbox" defaultChecked disabled className="rounded h-3 w-3 text-[#0984E3]" /> Corrective
                    </label>
                    <label className="flex items-center gap-1">
                      <input type="checkbox" defaultChecked disabled className="rounded h-3 w-3 text-[#0984E3]" /> Analytics
                    </label>
                    <label className="flex items-center gap-1">
                      <input type="checkbox" disabled className="rounded h-3 w-3 text-[#0984E3]" /> Targeting
                    </label>
                  </div>
                )}

                <div className="mt-3 flex justify-end gap-1.5 text-[10px] font-bold">
                  <button className="px-2.5 py-1 text-slate-600 font-mono">Decline</button>
                  <button className="px-3.5 py-1 text-white rounded font-mono transition-opacity hover:opacity-90" style={{ backgroundColor: primaryBrandColor, borderRadius: `${borderRadius - 4}px` }}>
                    Accept All
                  </button>
                </div>
              </div>
            </div>

            <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 flex justify-between items-center text-[10px] font-mono text-slate-500">
              <span className="flex items-center gap-1 shrink-0">
                <CheckCircle className="h-3 w-3 text-emerald-600" /> Style Integrity Checked
              </span>
              <span>CDN propagation delay: &lt;1.2s</span>
            </div>
          </div>
        </section>


        {/* ================= PANEL 3: IMMUTABLE VERSION CONTROL & PUBLIC HISTORY VAULT LEDGER ================= */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-xs p-5" id="compliance_timeline_ledger">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-4 border-b border-slate-100">
            <div className="space-y-1">
              <span className="bg-[#6C5CE7]/10 text-[#6C5CE7] text-[9px] uppercase font-black tracking-widest px-2 py-0.5 rounded-full font-mono">
                Audit Trail Vault
              </span>
              <h3 className="text-base font-extrabold text-slate-900 font-display">
                Immutable Version Control & Public History Vault Ledger
              </h3>
              <p className="text-xs text-slate-500 font-medium">
                Review comparative version history and cryptographic audit trails used as courtroom indicators in the event of regulatory litigation.
              </p>
            </div>
            
            <span className="bg-slate-900 text-white text-[10px] font-mono font-bold py-1 px-3 rounded-lg flex items-center gap-1.5 shadow-sm">
              <Terminal className="h-3.5 w-3.5 text-emerald-500" /> blockchain_ledger_ready: encrypted
            </span>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 sm:gap-6 mt-5">
            {/* Timeline sidebar picker */}
            <div className="lg:col-span-5 space-y-3">
              {diffs.map((diff, index) => (
                <button
                  key={index}
                  onClick={() => setActiveDiffIndex(index)}
                  className={`w-full text-left p-3.5 rounded-xl border transition-all flex flex-col gap-2 cursor-pointer ${
                    activeDiffIndex === index 
                      ? 'bg-[#6C5CE7]/5 border-[#6C5CE7] shadow-xs'
                      : 'bg-slate-50/50 hover:bg-slate-55 border-slate-200'
                  }`}
                >
                  <div className="flex justify-between items-center text-[10.5px] font-mono">
                    <span className="font-bold text-[#6C5CE7]">{diff.date}</span>
                    <span className="font-mono bg-white text-slate-500 px-1.5 py-0.5 border border-slate-200 rounded text-[9px]">
                      {diff.sha}
                    </span>
                  </div>
                  <h4 className="text-xs font-extrabold text-slate-900 leading-tight">
                    {diff.summary}
                  </h4>
                  <div className="text-[10px] text-slate-400 font-mono font-medium py-1 px-2.5 bg-white border border-slate-200/50 rounded-lg flex items-center gap-1.5">
                    <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 inline-block" />
                    Verified SHA-256 System Timestamp Lock
                  </div>
                </button>
              ))}
            </div>

            {/* Comparison view pane (GitHub styling compare) */}
            <div className="lg:col-span-7 space-y-3">
              <div className="border border-slate-200 rounded-xl overflow-x-auto shadow-xs bg-slate-900">
                <div className="p-3 bg-slate-950 border-b border-slate-800 flex justify-between items-center text-[10px] font-mono text-slate-450">
                  <span className="font-bold text-[#6C5CE7]">COMPARISON DIFF: {diffs[activeDiffIndex].summary}</span>
                  <span>Unified diff layout</span>
                </div>

                <div className="p-4 font-mono text-[11px] leading-relaxed space-y-3 max-h-56 overflow-y-auto">
                  {/* Deleted version */}
                  <div className="bg-rose-950/45 text-rose-300 p-3 rounded-lg border-l-4 border-rose-500 relative">
                    <span className="absolute top-2 right-2 text-[8px] bg-rose-900 text-rose-100 px-1.5 py-0.5 rounded">
                      DELETED CONTENT
                    </span>
                    <p className="pr-12 select-none">- {diffs[activeDiffIndex].removed}</p>
                  </div>

                  {/* Added version */}
                  <div className="bg-emerald-950/45 text-emerald-300 p-3 rounded-lg border-l-4 border-emerald-500 relative">
                    <span className="absolute top-2 right-2 text-[8px] bg-emerald-900 text-emerald-100 px-1.5 py-0.5 rounded font-black">
                      ADDED COMPLIANCE
                    </span>
                    <p className="pr-12">+ {diffs[activeDiffIndex].added}</p>
                  </div>
                </div>

                <div className="p-2.5 bg-slate-950 text-slate-500 text-[9.5px] font-mono flex justify-between">
                  <span>Cryptographic signature verified</span>
                  <span>9Xen Regulettee Ledger-V5.4</span>
                </div>
              </div>
            </div>
          </div>
        </section>


        {/* ================= PANEL 4: ENTERPRISE WHITE-LABEL BRANDING & THEME PERSONALIZATION CMS ================= */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden" id="whitelabel_branding_cms">
          <div className="p-5 border-b border-slate-100 bg-slate-50/50 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div className="space-y-1">
              <h3 className="text-xs font-black tracking-widest text-[#0984E3] uppercase font-mono flex items-center gap-1.5">
                <Palette className="h-4 w-4" /> Identity Studio Control Panel
              </h3>
              <p className="text-xs text-slate-500 font-medium">
                Configure corporate styling parameters, map custom domains, and update branding values for localized dashboards.
              </p>
            </div>
            
            <button
              onClick={handleApplyBranding}
              className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-mono font-black flex items-center gap-2 cursor-pointer shadow-sm transition-all"
            >
              <Save className="h-4 w-4 text-emerald-400" /> Apply Corporate Theme
            </button>
          </div>

          <AnimatePresence>
            {brandingNotification && (
              <motion.div 
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0 }}
                className="overflow-hidden"
              >
                <div className="mx-5 mt-4 p-3.5 bg-emerald-50 border border-emerald-200 text-emerald-805 rounded-xl text-xs font-bold tracking-tight flex items-center gap-1.5 animate-fadeIn">
                  <Check className="h-4 w-4 text-emerald-600 font-extrabold shrink-0" />
                  <span>{brandingNotification}</span>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          <div className="p-5 grid grid-cols-1 md:grid-cols-12 gap-4 sm:gap-6">
            
            {/* Domain & webhook inputs */}
            <div className="md:col-span-4 space-y-4">
              <div className="space-y-1.5">
                <label className="text-[10px] font-black text-slate-400 uppercase font-mono block">CUSTOM HOSTNAME DOMAIN</label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400 font-mono text-[10px]">
                    https://
                  </span>
                  <input
                    type="text"
                    value={customDomain}
                    onChange={(e) => setCustomDomain(e.target.value)}
                    className="w-full pl-14 pr-4 py-2 bg-slate-50 text-xs border border-slate-200 rounded-xl outline-none focus:ring-1 focus:ring-[#0984E3] text-slate-800 font-mono font-semibold"
                  />
                </div>
                <span className="text-[9px] text-slate-400 font-mono block">CNAME parameter maps compliance proxy portals.</span>
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-black text-slate-400 uppercase font-mono block">WEBHOOK ENDPOINT SECRET</label>
                <input
                  type="text"
                  value={webhookUrl}
                  onChange={(e) => setWebhookUrl(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-50 text-xs border border-slate-200 rounded-xl outline-none focus:ring-1 focus:ring-[#0984E3] text-slate-800 font-mono font-semibold"
                />
                <span className="text-[9px] text-slate-400 font-mono block">Dynamic Content Delivery Edge Network CDN Cache Reset trigger.</span>
              </div>
            </div>

            {/* Styling values customizable (Hex colors, sliders, fonts) */}
            <div className="md:col-span-4 space-y-4">
              <div className="space-y-1.5">
                <label className="text-[10px] font-black text-slate-400 uppercase font-mono block">Corporate Base Tone Hex</label>
                <div className="flex gap-2">
                  <input
                    type="color"
                    value={primaryBrandColor}
                    onChange={(e) => setPrimaryBrandColor(e.target.value)}
                    className="h-9 w-12 border border-slate-200 rounded-xl cursor-pointer p-0 bg-transparent shrink-0"
                  />
                  <input
                    type="text"
                    value={primaryBrandColor}
                    onChange={(e) => setPrimaryBrandColor(e.target.value)}
                    className="w-full px-3 py-2 bg-slate-50 text-xs border border-slate-200 rounded-xl outline-none focus:ring-1 focus:ring-[#0984E3] text-slate-800 font-mono font-semibold uppercase"
                  />
                </div>
              </div>

              <div className="space-y-1.5">
                <div className="flex justify-between items-center text-[10px] font-black text-slate-400 uppercase font-mono">
                  <label>Portal Border-Radius</label>
                  <span>{borderRadius}px</span>
                </div>
                <input
                  type="range"
                  min="0"
                  max="24"
                  value={borderRadius}
                  onChange={(e) => setBorderRadius(parseInt(e.target.value))}
                  className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#0984E3]"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-black text-slate-400 uppercase font-mono block">Typography Font Family</label>
                <select
                  value={typographyFont}
                  onChange={(e) => setTypographyFont(e.target.value)}
                  className="w-full px-3 py-1.5 bg-slate-50 border border-slate-200 text-xs rounded-lg outline-none"
                >
                  <option value="sans">Inter Sans (Modern Standard)</option>
                  <option value="mono">JetBrains Mono (Technical Spec)</option>
                  <option value="serif">Playfair Display (Corporate Editorial)</option>
                </select>
              </div>
            </div>

            {/* Logo uploads drag drop */}
            <div className="md:col-span-4 space-y-2">
              <span className="text-[10px] font-black text-slate-400 uppercase font-mono block">CLIENT LOGO UPLOAD DRAGZONE</span>
              <div 
                onClick={() => setIsLogoUploaded(!isLogoUploaded)}
                className="border-2 border-dashed border-slate-300 hover:border-[#0984E3] rounded-xl p-5 text-center bg-slate-50/50 hover:bg-slate-50 cursor-pointer transition-all flex flex-col items-center justify-center gap-1.5"
              >
                <Upload className="h-5 w-5 text-slate-400" />
                <div className="text-[10.5px] font-extrabold text-slate-700">
                  {isLogoUploaded ? '✓ compliance_logo_dark.svg' : 'Click to Upload Custom Logo asset'}
                </div>
                <p className="text-[9px] text-slate-450 leading-tight">
                  Supports SVGs, transparent PNGs up to 2MB. Dynamic resizing is managed.
                </p>
              </div>

              <div className="p-3 bg-blue-50 border border-blue-100 rounded-xl space-y-1">
                <span className="text-[9.5px] font-extrabold text-blue-800 font-mono flex items-center gap-1">
                  <AlertCircle className="h-3 w-3" /> Custom CSS Override
                </span>
                <p className="text-[9px] text-blue-700 leading-normal">
                  9Xen Regulettee portals load clean baseline rules parameters, ensuring fully compliant layouts with no unstyled flashes for visitors.
                </p>
              </div>
            </div>

          </div>

          <div className="p-3.5 bg-slate-50 border-t border-slate-100 flex flex-col md:flex-row justify-between items-center text-[10px] font-mono text-slate-500 gap-2">
            <span>Corporate API key pairing: Active</span>
            <span className="text-[#0984E3] font-bold">compliance-whitelabel-v1_config_manifest</span>
          </div>
        </section>
          </>
        )}

      </div>
    </div>
  );
}
